kind: Service
apiVersion: v1
metadata:
  name: animal-service
spec:
  selector:
    app: animals
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
